collate_fn:
  _target_: scr.data.dataset.AugmentationCollator
  augmentations:
    _target_: torchvision.transforms.v2.RandomChoice
    transforms:
    - _target_: torchvision.transforms.v2.MixUp
      num_classes: ${num_classes}
      alpha: 1.0
    - _target_: torchvision.transforms.v2.CutMix
      num_classes: ${num_classes}
      alpha: 1.0
    p:
    - 0.5
    - 0.5