transforms:
  _target_: torchvision.transforms.v2.Compose
  transforms:
  - _target_: scr.data.dataset.UnsqueezeTransform
  - _target_: torchvision.transforms.v2.Resize
    interpolation: 3
    size:
    - 224
    - 224
  - _target_: scr.data.dataset.DuplicateChannels
  - _target_: torchvision.transforms.v2.Normalize
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225