

experiment_number: 4 # unique experiment number
  # folder in mlflow and in output

data_dir: '/home/evgenshuben/Desktop/gitReps/YandexCup24/dataset'
file_ext: "npy"
num_classes: 39535


hydra:
  run:
    dir: ./outputs_val/run-${experiment_number}/hydra

mlflow:
  uri: "http://127.0.0.1:8080"
  experiment_name: "PipelineBackBones" # folder in mlflow and in output
  experiment_number: ${experiment_number}

enviroment:
  progress_bar: true
  device: "cuda"
  num_channels: 1


pipeline:
  model_ckpt: null # path to model if needs to checkpoint (in train or in test)
  patience: 4
  epochs: 20
  progress_bar: true
  log_steps: 100
  save_val_outputs: true
  output_dir: outputs_val/run-${experiment_number}/data # local path to dir wich will save logs and model ckpt's
  test_output_dir: outputs_test # dir in with save submits for
  save_model_path: models


defaults:
  - transforms/image  # default or image
  - transforms/augmentations
  - transforms/dataloader_classifier_collator_mixup_cutmix # это только для изображений
  - dataset/Classifier  # Classifier or MetricLearning
  - losses/cross_entropy
  - losses/triplet
  - model/backbone
  - optimizer/adamW


losses_weight:
  cross_entropy: 1.0
  triplet: 0.0

