experiment_number: 1 # unique experiment number
data_dir: '/home/evgeny.shubochkin/dataset'
file_ext: "npy"
num_classes: 39535


hydra:
  run:
    dir: ./outputs_val/run-${experiment_number}/hydra

mlflow:
  uri: "http://127.0.0.1:8080"
  experiment_name: "ResNet50" # folder in mlflow
  experiment_number: ${experiment_number}

enviroment:
  progress_bar: true
  device: "cuda" # cuda or cpu
  num_channels: 1


pipeline:
  model_ckpt: null # path to model if needs to checkpoint (in train or in test)
  patience: 4
  epochs: 1
  progress_bar: true
  log_steps: 100
  save_val_outputs: true
  output_dir: outputs_val/run-${experiment_number}/data # local path to dir wich will save logs and model ckpt's
  test_output_dir: outputs_test # dir in with save submits for
  save_model_path: models


defaults:
  - transforms/image  # default or image
  - transforms/augmentations
  - dataset/MetricLearning  # Classifier or MetricLearning
  - losses/cross_entropy
  - losses/triplet
  - model/backbone
  - optimizer/adamW


losses_weight:
  cross_entropy: 1.0
  triplet: 1.0

